agendamanha/afirmacoes/urls.py
from django.urls import path
from agendamanha.afirmacoes import views

app_name = 'afirmacoes'
urlpatterns = [
    path('', views.afirmacoes, name='afirmacoes'),
    path('add_afirmacao', views.add_afirmcao, name='add_afirmacao'),
    path('edit_afirmacao/<int:afirmacao_id>', views.edit_afirmacao, name='edit_afirmacao'),
    path('del_afirmacao/<int:afirmacao_id>', views.del_afirmacao, name='del_afirmacao'),
]

agendamanha/base/urls.py
from django.urls import path
from agendamanha.base import views

app_name = 'base'
urlpatterns = [
    path('', views.home, name='home')
]

agendamanha/diario/urls.py
from django.urls import path
from agendamanha.diario import views

app_name = 'diario'
urlpatterns = [
    path('', views.diario, name='diario'),
    path('add_entrada', views.add_entrada, name='add_entrada'),
    path('edit_entrada/<int:entrada_id>', views.edit_entrada, name='edit_entrada'),
    path('del_entrada/<int:entrada_id>', views.del_entrada, name='del_entrada'),
]

agendamanha/tarefas/urls.py
from django.urls import path
from agendamanha.tarefas import views

app_name = 'tarefas'
urlpatterns = [
    path('', views.terefas, name='tarefas'),
    path('<int:tarefa_id>', views.terefa, name='tarefa'),
    path('add_tarefa', views.add_tarefa, name='add_tarefa'),
    path('edit_tarefa/<int:tarefa_id>', views.edit_tarefa, name='edit_terefa'),
    path('del_tarefa/<int:tarefa_id>', views.del_tarefa, name='del_tarefa'),

]

agendamanha/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('agendamanha.base.urls')),
    path('users/', include('agendamanha.users.urls')),
    path('afirmacoes/', include('agendamanha.afirmacoes.urls')),
    path('diario/', include('agendamanha.diario.urls')),
    path('tarefas/', include('agendamanha.tarefas.urls')),
]

agendamanha/users/urls.py
from django.urls import path, include
from agendamanha.users import views

app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('sair_login', views.sair_login, name='sair_login'),
    path('register/', views.register, name='register'),

]

agendamanha/base/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.db import models
from django.utils import timezone
from django.core.mail import send_mail
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    App base User class.
    Email and password are required. Other fields are optional.
    """
    username_validator = UnicodeUsernameValidator()

    username = models.CharField(
        _('username'),
        max_length=150,
        unique=True,
        help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )

    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s' % (self.first_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

agendamanha/base/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'base/index.html')

agendamanha/base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block titulo %}Agenda manhã!{% endblock titulo %}</title>

    <meta name="description" content="Página do web site agenda manhã">
    <meta name="author" content="Eduardo Bazler">
    <link rel="icon" type="image/png" href="{% static 'img/favicon.ico' %}">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>


  </head>
  <body>

<div class="select2-container--classic">
	<div class="row">
		<div class="col-md-12">
			<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
              <a class="navbar-brand" href="{% url 'base:home' %}">Home</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>

              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
							 <a class="nav-link" href='{% url 'afirmacoes:afirmacoes' %}'>Afirmações</a>
						</li>
                    <li class="nav-item">
							 <a class="nav-link" href='{% url 'diario:diario' %}'>Diário</a>
						</li>
                    <li class="nav-item">
							 <a class="nav-link" href='{% url 'tarefas:tarefas' %}'>Tarefas</a>
						</li>
                    {% endif %}
                </ul>
                    {% if user.is_authenticated %}
                        <ul class="nav justify-content-end">
                            <li class="nav-item" style="margin: auto;">
                                 <a class="text-white">Conta - {{ user.email }}</a>
                            </li>
                            <li class="nav-item" style="margin-left: 10px;">
                                 <a class="nav-link btn bg-light" href="{% url 'users:sair_login' %}">Log out</a>
                            </li>
                        </ul>
                    {% else %}
                        <ul class="nav justify-content-end">
                              <li class="nav-item">
                                <a class="nav-link btn bg-light"  href="{% url 'users:login' %}">Log in</a>
                              </li>
                              <li class="nav-item" style="margin-left: 5px;">
                                  <a class="nav-link btn bg-light" href="{% url 'users:register' %}">Registrar-se</a>

                              </li>
                        </ul>

                    {% endif %}

              </div>
            </nav>
        </div>
    </div>
</div>
<div>
{% block body %}
{% endblock body %}
</div>
    {% block footer %}{% endblock footer %}

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>

  </body>
</html>

agendamanha/base/templates/base/footer.html
<footer class="main-footer" style="color: #ffefef;">
        <div class="container-fluid" >
            <div class="row"  >
                <div class="col-md-12" style="margin-top: 15px; margin-left: unset;">
                    <h3>Entre em contato</h3>
                    <address>
                        +55 12 996716167
                        <br>
                        <a href="https://www.linkedin.com/in/eduardo-bazler-782495127/" target="_blank">Linkedin: Eduardo Bazler</a>
                    </address>
                </div>
            </div>
        </div>
        <div class="container-fluid" style="background-color: #1b1b1b;">
            <div class="row">
                <div class="col-md-12" style="padding: 5px; margin-left: 5px;">
                    {% now 'Y' %} Agenda Manhã. Todos os direitos reservados.

                </div>
            </div>
        </div>
    </footer>

agendamanha/base/templates/base/index.html
{% extends 'base/base.html' %}
{%  load static %}
{% block titulo %}Agenda manhã - Home{% endblock %}
{% block body %}
    <div class="jumbotron">
				<h1 class="text-primary">
					Afirmações.
				</h1>
				{% include 'afirmacoes/frase_afirmacao.html' %}
				<p>
					<a class="btn btn-primary btn-large" href="{% url 'afirmacoes:afirmacoes' %}">Ver afirmações</a>
				</p>
			</div>
{#			<div class="carousel slide" id="carousel-956958">#}
{#				<ol class="carousel-indicators">#}
{#					<li data-slide-to="0" data-target="#carousel-956958">#}
{#					</li>#}
{#					<li data-slide-to="1" data-target="#carousel-956958">#}
{#					</li>#}
{#					<li data-slide-to="2" data-target="#carousel-956958" class="active">#}
{#					</li>#}
{##}
{#				</ol>#}
{#				<div class="carousel-inner">#}
{#					<div class="carousel-item">#}
{#						<img class="d-block w-100" alt="Carousel Bootstrap First" src="{% static 'img/pexels-maxime-francis-2246476 (cópia).jpg' %}" style="shape-image-threshold: 10%;">#}
{#						<div class="carousel-caption" style="margin: auto">#}
{#							<h4>#}
{#								Minha atividade preferida#}
{#							</h4>#}
{#							<p>#}
{#								Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.#}
{#							</p>#}
{#						</div>#}
{#					</div>#}
{#					<div class="carousel-item">#}
{#						<img class="d-block w-100" alt="Carousel Bootstrap Second" src="{% static 'img/pexels-sanaan-mazhar-3075993.jpg' %}">#}
{#						<div class="carousel-caption">#}
{#							<h4>#}
{#								Second Thumbnail label#}
{#							</h4>#}
{#							<p>#}
{#								Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.#}
{#							</p>#}
{#						</div>#}
{#					</div>#}
{#					<div class="carousel-item active">#}
{#						<img class="d-block w-100" alt="Carousel Bootstrap Third"#}
{#                             src="{% static 'img/pexels-vlad-alexandru-popa-1402787.jpg' %}"#}
{#                        >#}
{#						<div class="carousel-caption">#}
{#							<h4>#}
{#								Third Thumbnail label#}
{#							</h4>#}
{#							<p>#}
{#								Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.#}
{#							</p>#}
{#						</div>#}
{#					</div>#}
{##}
{#				</div> <a class="carousel-control-prev" href="#carousel-956958" data-slide="prev"><span class="carousel-control-prev-icon"></span> <span class="sr-only">Previous</span></a> <a class="carousel-control-next" href="#carousel-956958" data-slide="next"><span class="carousel-control-next-icon"></span> <span class="sr-only">Next</span></a>#}
{#			</div>#}
		</div>
	</div>
    <div class="minha-row jumbotron">
        <div class="row">
            <div class="col-md-4">
                <h2 class="text-primary">
                    Diário
                </h2>
                <p>
                    Este espaço é dedicado para criar um diário de uso pessoal. <br>
                    Para criar o hábito de escrever todas as manhãs e anotas todas as ideias que
                    vierem à sua cabeça em qualquer lugar.
                </p>
                <p>
                    <a class="btn btn-primary" href="{% url 'diario:diario' %}">Ver diário »</a>
                </p>
            </div>
            <div class="col-md-4 ju">
                <h2>
                    Heading
                </h2>
                <p>
                    Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
                </p>
                <p>
                    <a class="btn" href="#">View details »</a>
                </p>
            </div>
            <div class="col-md-4">
                <h2>
                    Heading
                </h2>
                <p>
                    Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
                </p>
                <p>
                    <a class="btn" href="#">View details »</a>
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock body%}
{%  block footer %}
    {% include 'base/footer.html' %}
{% endblock footer %}