agendamanha/diario/urls.py
from django.urls import path
from agendamanha.diario import views

app_name = 'diario'
urlpatterns = [
    path('', views.diario, name='diario'),
    path('add_entrada', views.add_entrada, name='add_entrada'),
    path('edit_entrada/<int:entrada_id>', views.edit_entrada, name='edit_entrada'),
    path('del_entrada/<int:entrada_id>', views.del_entrada, name='del_entrada'),
]

agendamanha/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('agendamanha.base.urls')),
    path('users/', include('agendamanha.users.urls')),
    path('afirmacoes/', include('agendamanha.afirmacoes.urls')),
    path('diario/', include('agendamanha.diario.urls')),
    path('tarefas/', include('agendamanha.tarefas.urls')),
]

agendamanha/diario/models.py
from django.db import models
from django import forms

from agendamanha.base.models import User


class Diario(models.Model):
    """Campo para escrever um diário"""
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    date_update = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.text[:50]}..."


class DiarioForm(forms.ModelForm):
    class Meta:
        model = Diario
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

agendamanha/diario/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404

from agendamanha.diario.models import Diario, DiarioForm


def check_entrada_owner(entrada, request):
    if entrada.owner != request.user:
        raise Http404


@login_required
def diario(request):
    """Mostra todas as afirmações."""
    entradas_list = Diario.objects.filter(owner=request.user).order_by('-date_added')

    paginator = Paginator(entradas_list, 2)

    page = request.GET.get('page')

    entradas = paginator.get_page(page)

    context = {'entradas': entradas}
    return render(request, 'diario/diario.html', context)


@login_required
def add_entrada(request):
    """Add nova entrada no diário"""
    if request.method != 'POST':
        form = DiarioForm
    else:
        form = DiarioForm(data=request.POST)
        if form.is_valid():
            nova_entrada = form.save(commit=False)
            nova_entrada.owner = request.user
            nova_entrada.save()
            return redirect('diario:diario')

    context = {'form': form}
    return render(request, 'diario/add_entrada.html', context)


@login_required
def edit_entrada(request, entrada_id):
    entrada = get_object_or_404(Diario, id=entrada_id)

    check_entrada_owner(entrada, request)

    if request.method != 'POST':
        form = DiarioForm(instance=entrada)
    else:
        form = DiarioForm(instance=entrada, data=request.POST)
        if form.is_valid():
            form.save()

            return redirect('diario:diario')

    context = {'entrada': entrada, 'form': form}
    return render(request, 'diario/edit_entrada.html', context)


@login_required
def del_entrada(request, entrada_id):
    entrada = get_object_or_404(Diario, id=entrada_id)

    check_entrada_owner(entrada, request)

    entrada.delete()

    messages.info(request, 'Entrada do diário deletada com sucesso.')

    return redirect('diario:diario')

agendamanha/diario/templates/diario/add_entrada.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% block body %}
    <main role="main" class="container">
    <div class="card text-center pb-2 mb-2 border-bottom">
      <div class="card-header">
      </div>
      <div class="card-body">
        <h1 class="card-title text-dark">Diário</h1>
        {% include 'diario/frase_diario.html' %}
      </div>
    </div>

        <form action="{% url 'diario:add_entrada' %}" method='post'>
            {% csrf_token %}
            <div class="card">
                  <div class="card-body">
                        <blockquote class="blockquote">
                          <h5 class="text-primary">Entrada do dia:</h5>
                          <p>{{ form.text|as_crispy_field}}</p>
                            <button type="submit" class="btn btn-primary">Adicionar</button>
                        </blockquote>
                  </div>
            </div>
        </form>

    </main>

{% endblock body %}

agendamanha/diario/templates/diario/diario.html
{% extends 'base/base.html' %}
{% load static %}
{% block body %}

    <main role="main" class="container">
    <div class="card text-center pb-2 mb-2 border-bottom">
      <div class="card-header">
      </div>
      <div class="card-body">
        <h1 class="card-title">Diário</h1>
        {% include 'diario/frase_diario.html' %}
        <a href="{% url 'diario:add_entrada' %}" class="btn btn-primary">Add entrada.</a>
      </div>
    </div>


{#    Cabeçalho #}

        <div>
        {% if messages %}
            {% for massage in messages %}
                <h2 {% if massage.tags %}class="alert alert-success" {% endif %}>{{ massage }}</h2>
            {% endfor %}
        {% endif %}
        {% for entrada in entradas %}
                <div class="card mb-3">
                      <div class="card-header">
                        <h3 class="text-primary">{{ entrada.date_added | date:'d/m/Y - (D)' }}</h3>
                      </div>
                      <div class="card-body">
                        <blockquote class="blockquote">
                          <p>{{ entrada.text | linebreaks }}</p>
                          <footer class="blockquote-footer">Data de atualização: <cite title="Source Title">{{ entrada.date_update }}</cite></footer>
                            <a href="{% url 'diario:edit_entrada' entrada.id %}" class="btn btn-primary" style="margin-top: 10px;">Editar</a>
                        </blockquote>
                      </div>
                </div>
            {% empty %}
                <div class="card">
                      <div class="card-header">
                        <h3 class="text-black-50">Não há afirmações para serem axibidas.</h3>
                      </div>
                </div>
            {% endfor %}
        </div>
        <div class="pagination">
            <span class="step-links">
                {% if entradas.has_previous %}
                    <a href="?page={{ entradas.previous_page_number }}">
                        <i class="fas fa-arrow-left"></i>
                    </a>
                {% endif %}

                <span class="current">
                    {{ entradas.number }} de {{ entradas.paginator.num_pages }}
                </span>

                {% if entradas.has_next %}
                    <a href="?page={{ entradas.next_page_number }}">
                        <i class="fas fa-arrow-right"></i>
                    </a>
                {% endif %}
            </span>

        </div>
    </main>

{% endblock body %}

agendamanha/diario/templates/diario/edit_entrada.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% block body %}
    <main role="main" class="container">
    <div class="card text-center pb-2 mb-2 border-bottom">
      <div class="card-header">
      </div>
      <div class="card-body">
        <h1 class="card-title text-dark">Diário</h1>
        {% include 'diario/frase_diario.html' %}
      </div>
    </div>

    <form action="{% url 'diario:edit_entrada' entrada.id %}" method='post'>

        {% csrf_token %}
        <div class="card">
              <div class="card-body">
                 <h2 class="text-primary">{{ entrada.date_added }}</h2>
              </div>
              <div class="card-body">
                    <blockquote class="blockquote">
                      <h5 class="text-primary">Entrada:</h5>
                      <p>{{ form.text|as_crispy_field}}</p>
                        <button type="submit" class="btn btn-primary">Adicionar</button>
                        <a href="{% url 'diario:del_entrada' entrada.id %}" class="btn btn-danger delete-btn-entrada">Deletar</a>
                    </blockquote>
              </div>
        </div>
    </form>

    </main>
{% endblock body %}

agendamanha/diario/templates/diario/frase_diario.html
<p class="card-text">
            O que quer que você escreva, colocar palavras em uma página é uma forma de terapia que não custa um centavo<br>
            Ideias podem vir de qualquer lugar, a qualuqer momento. O problema em fazer notas mentais é que a tinta some
            rapidamente.
</p>