agendamanha/afirmacoes/urls.py
from django.urls import path
from agendamanha.afirmacoes import views

app_name = 'afirmacoes'
urlpatterns = [
    path('', views.afirmacoes, name='afirmacoes'),
    path('add_afirmacao', views.add_afirmcao, name='add_afirmacao'),
    path('edit_afirmacao/<int:afirmacao_id>', views.edit_afirmacao, name='edit_afirmacao'),
    path('del_afirmacao/<int:afirmacao_id>', views.del_afirmacao, name='del_afirmacao'),
]

agendamanha/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('agendamanha.base.urls')),
    path('users/', include('agendamanha.users.urls')),
    path('afirmacoes/', include('agendamanha.afirmacoes.urls')),
    path('diario/', include('agendamanha.diario.urls')),
    path('tarefas/', include('agendamanha.tarefas.urls')),
]

agendamanha/afirmacoes/models.py
from django import forms
from django.db import models

from agendamanha.base.models import User


class Afirmacao(models.Model):
    """ ecreva suas afirmações com determinado tema"""
    titulo = models.CharField(max_length=100)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    date_update = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.text[:50]}..."


class AfirmacaoForm(forms.ModelForm):
    class Meta:
        model = Afirmacao
        fields = ['titulo', 'text']
        labels = {'titulo': '', 'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

agendamanha/afirmacoes/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from agendamanha.afirmacoes.models import Afirmacao, AfirmacaoForm
from django.contrib import messages


def check_afirmacao_owner(afirmacao, request):
    if afirmacao.owner != request.user:
        raise Http404


@login_required
def afirmacoes(request):
    """Mostra todas as afirmações."""
    afirmacoes_list = Afirmacao.objects.filter(owner=request.user).order_by('date_added')

    paginator = Paginator(afirmacoes_list, 3)

    page = request.GET.get('page')

    afirmacoes = paginator.get_page(page)

    context = {'afirmacoes': afirmacoes}
    return render(request, 'afirmacoes/afirmacoes.html', context)


@login_required
def add_afirmcao(request):
    """Add nova afirmação"""
    if request.method != 'POST':
        form = AfirmacaoForm
    else:
        form = AfirmacaoForm(data=request.POST)
        if form.is_valid():
            nova_afirmacao = form.save(commit=False)
            nova_afirmacao.owner = request.user
            nova_afirmacao.save()
            return redirect('afirmacoes:afirmacoes')

    context = {'form': form}
    return render(request, 'afirmacoes/add_afirmacao.html', context)


@login_required
def edit_afirmacao(request, afirmacao_id):
    afirmacao = get_object_or_404(Afirmacao, id=afirmacao_id)

    check_afirmacao_owner(afirmacao, request)

    if request.method != 'POST':
        form = AfirmacaoForm(instance=afirmacao)
    else:
        form = AfirmacaoForm(instance=afirmacao, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('afirmacoes:afirmacoes')

    context = {'afirmacao': afirmacao, 'form': form}
    return render(request, 'afirmacoes/edit_afirmacao.html', context)


@login_required
def del_afirmacao(request, afirmacao_id):
    afirmacao = get_object_or_404(Afirmacao, id=afirmacao_id)

    check_afirmacao_owner(afirmacao, request)

    afirmacao.delete()

    messages.info(request, 'Afirmação deletada com sucesso.')

    return redirect('afirmacoes:afirmacoes')

agendamanha/afirmacoes/templates/afirmacoes/add_afirmacao.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% block body %}
    <main role="main" class="container">
    <div class="card text-center pb-2 mb-2 border-bottom">
      <div class="card-header">
      </div>
      <div class="card-body">
        <h1 class="card-title text-dark">Afirmações</h1>
        {% include 'afirmacoes/frase_afirmacao.html' %}
      </div>
    </div>
    <form action="{% url 'afirmacoes:add_afirmacao' %}" method='post'>
        {% csrf_token %}
        <div class="card">
              <div class="card-body">
                 <h5 class="text-primary">Título: </h5>
                  {{ form.titulo|as_crispy_field }}
              </div>
              <div class="card-body">
                    <blockquote class="blockquote">
                      <h5 class="text-primary">Afirmação:</h5>
                      <p>{{ form.text|as_crispy_field}}</p>
                        <button type="submit" class="btn btn-primary">Adicionar</button>
                    </blockquote>
              </div>
        </div>
    </form>

    </main>
{% endblock body %}

agendamanha/afirmacoes/templates/afirmacoes/afirmacoes.html
{% extends 'base/base.html' %}
{% load static %}
{% block body %}

    <main role="main" class="container">
    <div class="card text-center pb-2 mb-2 border-bottom">
      <div class="card-header">
      </div>
      <div class="card-body">
        <h1 class="card-title">Afirmações</h1>
        {% include 'afirmacoes/frase_afirmacao.html' %}
        <a href="{% url 'afirmacoes:add_afirmacao' %}" class="btn btn-primary">Add afirmação</a>
      </div>
    </div>

    <div>
    {% if messages %}
        {% for massage in messages %}
            <h2 {% if massage.tags %}class="alert alert-success" {% endif %}>{{ massage }}</h2>
        {% endfor %}
    {% endif %}

    {% for afirmacao in afirmacoes %}
            <div class="card mb-3">
                  <div class="card-header">
                    <h3 class="text-primary">{{ afirmacao.titulo }}</h3>
                  </div>
                  <div class="card-body">
                    <blockquote class="blockquote">
                      <p>{{ afirmacao.text | linebreaks }}</p>
                      <footer class="blockquote-footer">Data de atualização: <cite title="Source Title">{{ afirmacao.date_update }}</cite></footer>
                        <a href="{% url 'afirmacoes:edit_afirmacao' afirmacao.id %}" class="btn btn-primary" style="margin-top: 10px;">Editar</a>
                    </blockquote>
                  </div>
            </div>
        {% empty %}
            <div class="card">
                  <div class="card-header">
                    <h3 class="text-black-50">Não há afirmações para serem axibidas.</h3>
                  </div>
            </div>
        {% endfor %}
    </div>
    <div class="pagination">
            <span class="step-links">
                {% if afirmacoes.has_previous %}
                    <a href="?page={{ afirmacoes.previous_page_number }}">
                        <i class="fas fa-arrow-left"></i>
                    </a>
                {% endif %}

                <span class="current">
                    {{ afirmacoes.number }} de {{ afirmacoes.paginator.num_pages }}
                </span>

                {% if afirmacoes.has_next %}
                    <a href="?page={{ afirmacoes.next_page_number }}">
                        <i class="fas fa-arrow-right"></i>
                    </a>
                {% endif %}
            </span>

        </div>

    </main>


{% endblock body %}

agendamanha/afirmacoes/templates/afirmacoes/edit_afirmacao.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% block body %}
    <main role="main" class="container">
    <div class="card text-center pb-2 mb-2 border-bottom">
      <div class="card-header">
      </div>
      <div class="card-body">
        <h1 class="card-title text-dark">Afirmações</h1>
        {% include 'afirmacoes/frase_afirmacao.html' %}
      </div>
    </div>
    <form action="{% url 'afirmacoes:edit_afirmacao' afirmacao.id %}" method='post'>

        {% csrf_token %}
        <div class="card">
              <div class="card-body">
                 <h5 class="text-primary">Título: </h5>
                  {{ form.titulo|as_crispy_field }}
              </div>
              <div class="card-body">
                    <blockquote class="blockquote">
                      <h5 class="text-primary">Afirmação:</h5>
                      <p>{{ form.text|as_crispy_field}}</p>
                        <button type="submit" class="btn btn-primary">Adicionar</button>
                        <a href="{% url 'afirmacoes:del_afirmacao' afirmacao.id %}" class="btn btn-danger delete-btn-afirmacao">Deletar</a>
                    </blockquote>
              </div>
        </div>
    </form>

    </main>

{% endblock body %}

agendamanha/afirmacoes/templates/afirmacoes/frase_afirmacao.html
<p class="card-text">
            Afirmações	são	uma	das	ferramentas	mais eficientes	para se	tornar	rapidamente a
            pessoa	que	você precisa ser para conquistar tudo o	que	deseja	na	vida.<br> Afirmações permitem que você
            projete	e depois desenvolva	o estado mental (pensamentos, crenças, concentração) de	que	precisa	para
            levar	qualquer área	de sua	vida	para o próximo nível.
</p>