agendamanha/tarefas/urls.py
from django.urls import path
from agendamanha.tarefas import views

app_name = 'tarefas'
urlpatterns = [
    path('', views.terefas, name='tarefas'),
    path('<int:tarefa_id>', views.terefa, name='tarefa'),
    path('add_tarefa', views.add_tarefa, name='add_tarefa'),
    path('edit_tarefa/<int:tarefa_id>', views.edit_tarefa, name='edit_terefa'),
    path('del_tarefa/<int:tarefa_id>', views.del_tarefa, name='del_tarefa'),

]

agendamanha/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('agendamanha.base.urls')),
    path('users/', include('agendamanha.users.urls')),
    path('afirmacoes/', include('agendamanha.afirmacoes.urls')),
    path('diario/', include('agendamanha.diario.urls')),
    path('tarefas/', include('agendamanha.tarefas.urls')),
]

agendamanha/tarefas/models.py
from django.db import models


class Tarefa(models.Model):

    STATUS = (
        ('fazendo', 'Fazendo'),
        ('feita', 'Feita'),
    )

    titulo = models.CharField(max_length=255)
    descricao = models.TextField()
    done = models.CharField(
        max_length=7,
        choices=STATUS,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.titulo

agendamanha/tarefas/forms.py
from django import forms
from .models import Tarefa


class TarefaForm(forms.ModelForm):

    class Meta:
        model= Tarefa
        fields = ('titulo', 'descricao')

agendamanha/tarefas/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from . models import Tarefa
from .forms import TarefaForm
from django.contrib import messages
from django.core.paginator import Paginator
# Create your views here.


def terefas(request):

    search = request.GET.get('search')

    if search:

        tarefas = Tarefa.objects.filter(titulo__icontains=search)

    else:
        tarefas_list = Tarefa.objects.all().order_by('-created_at')

        paginator = Paginator(tarefas_list, 5)

        page = request.GET.get('page')

        tarefas = paginator.get_page(page)

    contexto = {'tarefas': tarefas}

    return render(request, 'tarefas/tarefas.html', contexto)


def terefa(request, tarefa_id):
    tarefa = get_object_or_404(Tarefa, pk=tarefa_id)
    contexto = {'tarefa': tarefa}
    return render(request,'tarefas/tarefa.html', contexto)


def add_tarefa(request):
    if request.method == 'POST':
        form = TarefaForm(request.POST)

        if form.is_valid():
            tarefa = form.save(commit=False)
            tarefa.done = 'fazendo'
            tarefa.save()

            return redirect('tarefas:tarefas')

    else:
        form = TarefaForm()
        contexto = {'form': form}
    return render(request, 'tarefas/add_tarefa.html', contexto)


def edit_tarefa(request, tarefa_id):
    tarefa = get_object_or_404(Tarefa, pk=tarefa_id)
    form = TarefaForm(instance=tarefa)

    if request.method == 'POST':
        form = TarefaForm(request.POST, instance=tarefa)

        if form.is_valid():
            tarefa.save()
            return redirect('tarefas:tarefas')

        else:
            contexto = {'form': form, 'tarefa': tarefa}
            return render(request, 'tarefas/edit_tarefas.html', contexto)

    else:
        contexto = {'form': form, 'tarefa': tarefa}
        return render(request, 'tarefas/edit_tarefas.html', contexto)


def del_tarefa(request, tarefa_id):
    tarefa = get_object_or_404(Tarefa, pk=tarefa_id)
    tarefa.delete()

    messages.info(request, 'Tarefa deletada com sucesso.')

    return redirect('tarefas:tarefas')

agendamanha/tarefas/templates/tarefas/add_tarefa.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}


{%  block titulo %}
    Add_tarefa
{% endblock titulo %}

{%  block body %}
    <main role="main" class="container">
    <div class="card text-center pb-2 mb-2 border-bottom">
        <div class="card-header">
      </div>
      <div class="card-body">
        <h1 class="card-title">Lista de tarefas</h1>
{#        {% include 'afirmacoes/frase_afirmacao.html' %}#}
            Incluir texto de tarefas
      </div>
    </div>

{#    Aqui é onde começa a construção seguindo o vídeo#}

    <div class="card">


        <div class="card-header">
            <h1 class="text-primary">Adicione sua nova tarefa</h1>
        </div>
        <div class="list-div">
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" class="btn btn-success" value="Criar Tarefa">
            </form>
        </div>

    </div>

{% endblock body %}

agendamanha/tarefas/templates/tarefas/edit_tarefas.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}

{%  block titulo %}
    Edit_tarefa
{% endblock titulo %}

{%  block body %}
    <main role="main" class="container">
    <div class="card text-center pb-2 mb-2 border-bottom">
        <div class="card-header">
      </div>
      <div class="card-body">
        <h1 class="card-title">Lista de tarefas</h1>
{#        {% include 'afirmacoes/frase_afirmacao.html' %}#}
            Incluir texto de tarefas
      </div>
    </div>

{#    Aqui é onde começa a construção seguindo o vídeo#}

    <div class="card">


        <div class="card-header">
            <h1 class="text-primary">Edite sua tarefa</h1>
        </div>
        <div class="list-div">
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy}}
                <input type="submit" class="btn btn-success" value="Confirmar edição">
            </form>
        </div>

    </div>

{% endblock body %}

agendamanha/tarefas/templates/tarefas/tarefa.html
{% extends 'base/base.html' %}

{%  block titulo %}
    Tarefa
{% endblock titulo %}

{%  block body %}
    <main role="main" class="container">
    <div class="card text-center pb-2 mb-2 border-bottom">
        <div class="card-header">
      </div>
      <div class="card-body">
        <h1 class="card-title">Lista de tarefas</h1>
{#        {% include 'afirmacoes/frase_afirmacao.html' %}#}
            Incluir texto de tarefas
      </div>
    </div>

{#    Aqui é onde começa a construção seguindo o vídeo#}

    <div class="card">


        <div class="card-header">
            <h1 class="text-primary">{{ tarefa.titulo }}</h1>
        </div>
        <div class="list-div">

            <p>{{ tarefa.descricao | linebreaks}}</p>
        </div>

    </div>

{% endblock body %}

agendamanha/tarefas/templates/tarefas/tarefas.html
{% extends 'base/base.html' %}

{%  block titulo %}
    lista de tarefas
{% endblock titulo %}

{%  block body %}
    <main role="main" class="container">
    <div class="card text-center pb-2 mb-2 border-bottom">
        <div class="card-header">
      </div>
      <div class="card-body">
        <h1 class="card-title">Lista de tarefas</h1>
{#        {% include 'afirmacoes/frase_afirmacao.html' %}#}
            Incluir texto de tarefas
      </div>
    </div>

{#    Aqui é onde começa a construção seguindo o vídeo#}

    <div class="card">


        <div class="card-header">
            <h1 class="text-primary">Lista de tarefas</h1>
        </div>
        <div class="list-div">
            <a id="add-link" href="{% url 'tarefas:add_tarefa' %}">
                <div class="col-2 add-div">
                    <i class="fas fa-plus"></i> Adicionar tarefa
                </div>
            </a>
            <div class="col-9 search-div">
                <form method="GET" id="search-form">
                    <input class="form-control" type="text" id="search" name="search"
                           placeholder="Digine o nome da tarefa para buscar"
                           value="{{ request.GET.search }}">
                    <i class="fas fa-search" id="search-btn"></i>
                </form>
            </div>

            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li {% if message.tags %}class="alert alert-{{ message.tags}}" {% endif %}>{{ message }}</li>
                    {%  endfor %}
                </ul>
            {% endif %}

            {% for tarefa in tarefas %}
                <ul class="task-list">
                    <li class="task-item">
                        <a href="{% url 'tarefas:tarefa' tarefa.id %}"><span>{{ tarefa.titulo }}</span></a>

                        <a href="{% url 'tarefas:del_tarefa' tarefa.id %}" class="delete-btn-tarefa"><span><i class="fas fa-trash"></i></span></a>

                        <a href="{% url 'tarefas:edit_terefa' tarefa.id %}"><span><i class="fas fa-edit"></i></span></a>

                    </li>

                </ul>
            {% empty %}
                <ul class="task-list">
                    <li class="task-item">
                        <span>Não há terefas registradas ainda.</span>
                    </li>

                </ul>
            {% endfor %}

        </div>

        <div class="pagination">
            <span class="step-links">
                {% if tarefas.has_previous %}
                    <a href="?page={{ tarefas.previous_page_number }}">
                        <i class="fas fa-arrow-left"></i>
                    </a>
                {% endif %}

                {% if tarefas.paginator.num_pages %}
                <span class="current">
                    {{ tarefas.number }} de {{ tarefas.paginator.num_pages }}
                </span>
                {% endif %}

                {% if tarefas.has_next %}
                    <a href="?page={{ tarefas.next_page_number }}">
                        <i class="fas fa-arrow-right"></i>
                    </a>
                {% endif %}
            </span>

        </div>

    </div>

{% endblock body %}